version = 0.1

[default.global.parameters]
stack_name = "api-kosto-saas"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
resolve_s3 = true
disable_rollback = false
# Do not place secrets in plain text here if you are going to use GitHub Secrets
# The parameter will be passed from the GitHub workflow, not from here
