version = 0.1

[default.global.parameters]
stack_name = "api-kosto-saas"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
resolve_s3 = true
disable_rollback = false
# No pongas aquí el secreto en texto plano si vas a usar GitHub Secrets
# El parámetro se pasará desde el workflow de GitHub, no desde aquí